import bcrypt from 'bcryptjs';

const data = {
    users: [
       {
           name: 'Kevin',
           email: 'admin@example.com',
           password: bcrypt.hashSync('1234', 8),
           isAdmin: true,
       },
       {
            name: 'Aiman',
            email: 'user@example.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: false,
        },
    ],
    products:[
        {
            name: "A Song of Fire and Ice",
            category: 'Books',
            image: '/images/p1.jpg',
            price: 12,
            countInStock: 10,
            brand: '?',
            rating: 4.1,
            numReviews: 3,
            description: 'High quality book',
        },
        {
            name: "The Hunger Games",
            category: 'Books',
            image: '/images/p1.jpg',
            price: 13,
            countInStock: 20,
            brand: '?',
            rating: 4.2,
            numReviews: 11,
            description: 'High quality book',
        },
        {
            name: "To Kill a Mockingbird",
            category: 'Books',
            image: '/images/p1.jpg',
            price: 10,
            countInStock: 0,
            brand: '?',
            rating: 4.8,
            numReviews: 7,
            description: 'High quality book',
        },
        {
            name: "The Book Thief",
            category: 'Books',
            image: '/images/p1.jpg',
            price: 11,
            countInStock: 8,
            brand: '?',
            rating: 4.4,
            numReviews: 5,
            description: 'High quality book',
        },
        {
            name: "Animal Farm",
            category: 'Books',
            image: '/images/p1.jpg',
            price: 9,
            countInStock: 25,
            brand: '?',
            rating: 4.3,
            numReviews: 3,
            description: 'High quality book',
        },
        {
            name: "The Fault in Our Stars",
            category: 'Books',
            image: '/images/p1.jpg',
            price: 12,
            countInStock: 12,
            brand: '?',
            rating: 4.0,
            numReviews: 16,
            description: 'High quality book',
        }, 
    ],
};
export default data;