const data = {
    products:[
        {
            _id: '1',
            name: "A Song of Fire and Ice",
            category: 'Books',
            image: '/images/p1.jpg',
            price: 12,
            countInStock: 10,
            brand: '?',
            rating: 4.1,
            numReviews: 3,
            description: 'High quality book',
        },
        {
            _id: '2',
            name: "The Hunger Games",
            category: 'Books',
            image: '/images/p1.jpg',
            price: 13,
            countInStock: 20,
            brand: '?',
            rating: 4.2,
            numReviews: 11,
            description: 'High quality book',
        },
        {
            _id: '3',
            name: "To Kill a Mockingbird",
            category: 'Books',
            image: '/images/p1.jpg',
            price: 10,
            countInStock: 0,
            brand: '?',
            rating: 4.8,
            numReviews: 7,
            description: 'High quality book',
        },
        {
            _id: '4',
            name: "The Book Thief",
            category: 'Books',
            image: '/images/p1.jpg',
            price: 11,
            countInStock: 8,
            brand: '?',
            rating: 4.4,
            numReviews: 5,
            description: 'High quality book',
        },
        {
            _id: '5',
            name: "Animal Farm",
            category: 'Books',
            image: '/images/p1.jpg',
            price: 9,
            countInStock: 25,
            brand: '?',
            rating: 4.3,
            numReviews: 3,
            description: 'High quality book',
        },
        {
            _id: '6',
            name: "The Fault in Our Stars",
            category: 'Books',
            image: '/images/p1.jpg',
            price: 12,
            countInStock: 12,
            brand: '?',
            rating: 4.0,
            numReviews: 16,
            description: 'High quality book',
        },
    ],
};
export default data;